servers:
  node1: ec2-18-229-162-130.sa-east-1.compute.amazonaws.com
  node2: ec2-18-228-97-0.sa-east-1.compute.amazonaws.com
  node3: ec2-18-228-81-105.sa-east-1.compute.amazonaws.com

spring:
  zipkin:
    base-url: http://${servers.node3}:9411/
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      authentication-database: admin
      host: ${servers.node3}
      password: t1ck3ts305PK_1
      port: 10404
      username: admin
    rabbitmq:
      host: ${spring.mongodb.host}
      port: 5673
      username: auditor
      password: auditor2019
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: ${servers.node1}
    preferIpAddress: true
descuento:
  cantidad-compra:
    ident: DCC_MAXC
  cantidad-total:
    ident: DCC_MAXT
  tercera-edad:
    ident: DESC_3EDAD
attendance:
  entity:
    name: attendance
  host: http://${servers.node2}
  port: 8102
metadata:
  entity:
    name: metaDataCatalog
  host: http://${servers.node1}
  port: 8097
product:
  entity:
    name: product
  host: http://${servers.node2}
  port: 8090
fares:
  entity:
    name: fares
  host: http://${servers.node2}
  port: 8081
outlet:
  entity:
    name: outlet
  host: http://${servers.node2}
  port: 8103
delivery:
  entity:
    name: delivery
  host: http://${servers.node2}
  port: 8104
compensacion:
  entity:
    name: compensacion
  host: http://${servers.node2}
  port: 8199
migration:
  entity:
    name: migration
  host: http://${servers.node2}
  port: 8098
notification:
  entity:
    name: notification
  host: http://${servers.node2}
  port: 8281
charge:
  entity:
    name: charge
  host: http://${servers.node1}
  port: 8094
inventory:
  entity:
    name: inventory
  host: http://${servers.node1}
  port: 8099
customer:
  entity:
    name: customer
  host: http://${servers.node1}
  port: 8098
users:
  entity:
    name: users
  host: http://${servers.node1}
  port: 8081
revenue:
  entity:
    name: revenue
  host: http://${servers.node1}
  port: 8096
cert-manager:
  entity:
    name: cert-manager
  host: http://${servers.node3}
  port: 8009
elastic-search:
  entity:
    name: elastic-search
  host: http://${servers.node3}
  port: 9200
